package com.goldenleaf.shop.model;

import com.goldenleaf.shop.exception.EmptyNameException;

import jakarta.persistence.*;

/**
 * Entity representing a product category in the online shop.
 * <p>
 * Categories are used to group similar {@link Product} items (e.g., "Electronics", "Clothing", "Books").
 * Each category has a unique auto-generated identifier and a non-empty name with a maximum length of 100 characters.
 * </p>
 * <p>
 * This is a simple JPA entity mapped to the database table named {@code category}.
 * The {@code id} field is auto-incremented using the database's identity column strategy.
 * </p>
 *
 * @author GoldenLeaf Team
 * @see Product
 * @since 1.0
 */
@Entity
@Table(name = "category")
public class Category {

    /**
     * Unique identifier for the category.
     * <p>
     * Automatically generated by the database using identity strategy.
     * Cannot be manually set.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the category.
     * <p>
     * Must not be {@code null} or blank. Maximum length is 100 characters.
     * This field is mandatory and enforced both at the application and database levels.
     * </p>
     */
    @Column(nullable = false, length = 100)
    private String name;

    /** Default constructor required by JPA. */
    public Category() {}

    /**
     * Constructs a new category with the specified name.
     * <p>
     * The name is validated immediately upon construction.
     * </p>
     *
     * @param name the name of the category
     * @throws EmptyNameException if the name is {@code null} or blank (empty or whitespace-only)
     */
    public Category(String name) throws EmptyNameException {
        setName(name); // Reuse validation logic
    }

    /**
     * Returns the unique identifier of this category.
     *
     * @return the category ID, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }
    
    public void setId(Long id) {
		this.id = id;
		
	}

    /**
     * Returns the name of this category.
     *
     * @return the non-null, non-empty name of the category
     */
    public String getName() {
        return this.name;
    }

    /**
     * Updates the name of this category.
     * <p>
     * The new name must not be {@code null} or blank.
     * This method performs validation before assigning the value.
     * </p>
     *
     * @param name the new name for the category
     * @throws EmptyNameException if the provided name is {@code null}, empty, or consists only of whitespace
     */
    public void setName(String name) throws EmptyNameException {
        if (name == null || name.isBlank()) {
            throw new EmptyNameException("Name cannot be null or empty");
        }
        this.name = name.trim();
    }

    /**
     * Returns a string representation of the category.
     * <p>
     * Useful for logging and debugging.
     * </p>
     *
     * @return a string containing the category ID and name
     */
    @Override
    public String toString() {
        return "Category{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }

    /**
     * Indicates whether some other object is "equal to" this category.
     * <p>
     * Two categories are considered equal if they have the same non-null ID.
     * If ID is {@code null}, fallback to object reference comparison.
     * </p>
     *
     * @param o the reference object with which to compare
     * @return {@code true} if this object is the same as the obj argument; {@code false} otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Category category = (Category) o;
        return id != null && id.equals(category.id);
    }

    /**
     * Returns a hash code value for the category.
     * <p>
     * Consistent with {@link #equals(Object)} — based on the ID when available.
     * </p>
     *
     * @return a hash code value for this object
     */
    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : super.hashCode();
    }
}