package com.goldenleaf.shop.model;

import java.time.YearMonth;

import com.goldenleaf.shop.exception.*;

import jakarta.persistence.*;

/**
 * Entity representing a customer's credit/debit card used for payments.
 * <p>
 * Stores card details required for processing payments. The CVV is marked as {@code transient}
 * and is never persisted to the database for security reasons (PCI DSS compliance).
 * </p>
 * <p>
 * This entity has a mandatory many-to-one relationship with {@link Customer}.
 * Each card belongs to exactly one customer.
 * </p>
 *
 * @author GoldenLeaf Team
 * @see Customer
 * @since 1.0
 */
@Entity
@Table(name = "credit_card")
public class CreditCard {

    /**
     * Unique identifier for the credit card record.
     * <p>
     * Auto-generated by the database using identity strategy.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the cardholder as it appears on the card.
     * <p>
     * Must not be null or blank. Maximum length: 100 characters.
     * </p>
     */
    @Column(nullable = false, length = 100)
    private String holderName;

    /**
     * Credit card number (typically 13–19 digits).
     * <p>
     * Stored as plain text in this example. In production systems,
     * consider tokenization or encryption at rest (e.g., using vault solutions).
     * </p>
     */
    @Column(nullable = false, length = 19)
    private String cardNumber;

    /**
     * Card expiration date (month and year).
     * <p>
     * Represented as {@link YearMonth} to ensure valid date format.
     * Must not be null.
     * </p>
     */
    @Column(nullable = false)
    private YearMonth expiry;

    /**
     * Card Verification Value (CVV/CVC).
     * <p>
     * Marked as {@code transient} — this field is <strong>never persisted</strong> to the database
     * for security and PCI DSS compliance reasons.
     * It is only held in memory during payment processing and should be cleared immediately after use.
     * </p>
     */
    @Transient
    private String cvv;

    /**
     * The customer who owns this credit card.
     * <p>
     * Mandatory relationship — a card cannot exist without an associated customer.
     * </p>
     */
    @ManyToOne
    @JoinColumn(name = "customer_id", nullable = false)
    private Customer customer;

    /** Default constructor required by JPA. */
    public CreditCard() {}

    /**
     * Returns the unique database identifier of this card.
     *
     * @return the card ID, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the customer who owns this credit card.
     *
     * @return the associated {@link Customer}, never {@code null} after proper assignment
     */
    public Customer getCustomer() {
        return customer;
    }

    /**
     * Returns the cardholder's name.
     *
     * @return the name as printed on the card
     */
    public String getHolderName() {
        return holderName;
    }

    /**
     * Returns the credit card number.
     * <p>
     * Warning: In real production systems, consider masking (e.g., "•••• •••• •••• 7275")
     * when displaying or logging.
     * </p>
     *
     * @return full card number
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * Returns the card's expiration date.
     *
     * @return expiration {@link YearMonth}, never {@code null}
     */
    public YearMonth getExpiry() {
        return expiry;
    }

    /**
     * Returns the CVV code (only available in memory during active payment flow).
     *
     * @return the CVV, or {@code null} if not set or already cleared
     */
    public String getCvv() {
        return cvv;
    }

    /**
     * Assigns this card to a customer.
     * <p>
     * Establishes the ownership relationship. Customer must not be {@code null}.
     * </p>
     *
     * @param customer the owner of this card
     * @throws NullCustomerException if customer is {@code null}
     */
    public void setCustomer(Customer customer) throws NullCustomerException {
        if (customer == null) {
            throw new NullCustomerException("Customer cannot be null");
        }
        this.customer = customer;
    }

    /**
     * Sets the cardholder name.
     *
     * @param holderName name as it appears on the card
     * @throws EmptyNameException if the name is {@code null} or blank
     */
    public void setHolderName(String holderName) throws EmptyNameException {
        if (holderName == null || holderName.isBlank()) {
            throw new EmptyNameException("Holder name cannot be empty");
        }
        this.holderName = holderName.trim();
    }

    /**
     * Sets the credit card number.
     *
     * @param cardNumber the full card number (spaces or dashes optional)
     * @throws EmptyCardNumberException if the number is {@code null} or blank
     */
    public void setCardNumber(String cardNumber) throws EmptyCardNumberException {
        if (cardNumber == null || cardNumber.isBlank()) {
            throw new EmptyCardNumberException("Card number cannot be empty");
        }
        this.cardNumber = cardNumber.replaceAll("\\s|-", ""); // Normalize: remove spaces/dashes
    }

    /**
     * Sets the card expiration date.
     *
     * @param expiry expiration date as {@link YearMonth}
     * @throws EmptyExpiryException if expiry is {@code null}
     */
    public void setExpiry(YearMonth expiry) throws EmptyExpiryException {
        if (expiry == null) {
            throw new EmptyExpiryException("Expiry cannot be null");
        }
        this.expiry = expiry;
    }

    /**
     * Temporarily sets the CVV code during payment processing.
     * <p>
     * This value is held only in memory and never persisted.
     * </p>
     *
     * @param cvv the 3- or 4-digit security code
     * @throws EmptyCvvException if CVV is {@code null} or blank
     */
    public void setCvv(String cvv) throws EmptyCvvException {
        if (cvv == null || cvv.isBlank()) {
            throw new EmptyCvvException("CVV cannot be empty");
        }
        this.cvv = cvv.trim();
    }

    /**
     * Clears the CVV from memory after use (recommended for security).
     * <p>
     * Should be called immediately after the payment attempt succeeds or fails.
     * </p>
     */
    public void clearCvv() {
        this.cvv = null;
    }

    /**
     * Returns a masked version of the card number for display purposes.
     * <p>
     * Example: "•••• •••• •••• 1234"
     * </p>
     *
     * @return masked card number
     */
    public String getMaskedCardNumber() {
        if (cardNumber == null || cardNumber.length() < 4) {
            return "•••• •••• •••• ••••";
        }
        String last4 = cardNumber.substring(cardNumber.length() - 4);
        return "•••• •••• •••• " + last4;
    }

    @Override
    public String toString() {
        return "CreditCard{" +
                "id=" + id +
                ", holderName='" + holderName + '\'' +
                ", cardNumber='" + getMaskedCardNumber() + '\'' +
                ", expiry=" + expiry +
                ", customerId=" + (customer != null ? customer.getId() : "null") +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        CreditCard that = (CreditCard) o;
        return id != null && id.equals(that.id);
    }

    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }
}